### ISSUE TITLE
How to avoid slipping

### ISSUE THREAD

**Issue by Civile** [liabru/matter-js#109] opened 2015-07-01 19:01 UTC
Hi, I'm working on a character and I need to completely stop its speed when i release the button "run right". I've tried by setting his friction to 1 (maximum value) but without solving. It 'a test project that I am developing for my engine that uses the physics of Matter. Am i doing something wrong?
Eventually here you can find here the whole engine including the test (folder test -> gamestate.js -> player class) https://github.com/Civile/Duedo.js

Another problem that i found is: the camera translation (canvas translation) destabilizes all the body. Example, when the camera follows a sprite, everything (physics bodies) begins to slips.

Thank you

**Comment by Civile** [comment] 2015-07-01 19:40
About the first problem i solved setting the body position to its current position everytime i need it. This completely stops the body. But still don't know how to fix the second issue

**Comment by liabru** [comment] 2015-07-02 18:23
Upgrading to the latest [master build](https://github.com/liabru/matter-js/blob/master/build/matter.js) seems to resolve this - can you try it? (I think the cause was fixed in #76).

Also just a heads up: when you need to precisely control a body like that it's often better to use [Body.setVelocity](http://brm.io/matter-js-docs-master/classes/Body.html#method_setVelocity) on key down for every step, then after key up friction should slow the body down naturally as expected.

> Another problem that i found is: the camera translation (canvas translation) destabilizes all the body. 

Rendering shouldn't have any effect on the physics, do you have a jsfiddle for this?

**Comment by Civile** [comment] 2015-07-06 18:26
Ok, thank you very much, i'll try it and certainly let you know. In the meanwhile i will investigate that strange problem that seems to occur  during the translation of the canvas. It should be something else.

**Closed** 2015-12-05 18:25 UTC
