### ISSUE TITLE
Commonjs modules / Browserify

### ISSUE THREAD

**Issue by hfaulds** [liabru/matter-js#80] opened 2015-04-12 12:10 UTC
This was mostly motivated by my need to avoid including the Runner code into my codebase (to avoid window being referenced in node). Using commonjs modules and browserify allows me to require individual files (and automatically include their dependencies) from my project.

https://github.com/hfaulds/matter-js works fine and uses browserify to build the final code. The diff is a bit of a nightmare at the moment because there's no need to wrap everything in closures in each file (browserify does that for you) which changes the indentation in every src file.

I also removed trailing whitespace during this process.

I'm willing to work towards making a reviewable PR if there is any chance it would get merged (I notice there has been a few PRs open for a long time).

**Comment by liabru** [comment] 2015-04-12 23:00
Awesome, this has definitely been on my todo list (which is quite long) so I'll check this out soon!
I've recently been working on a rather large feature which is due to be merged soon, but if I decided to use this then I'd have to merge this first I think or it could get tricky.

**Comment by hfaulds** [comment] 2015-04-13 08:30
Ok, here's some steps this could be split into to make the PR more reviewable.

Step 1 should be easy but be a big diff.
Step 2 is slightly more involved but will be a short diff.
Step 3 is easy but another large diff.

If possible it would probably be easier to do this once there are no PRs to merge. My fork serves my purposes for now so I'm in no rush.

- [ ] Strip trailing whitespace (and make part of the jshint tests).

One could use a sed or something like https://www.npmjs.com/package/js-beautify. The latter might help people in my situation whose editors are set up for 2-space-tabs (and automatically convert tabs to spaces) as we can just run the beautify command after making changes, it may also help in step 3.

- [ ] add requires, `module.export` and browserify grunt task
The existing closures can be left at this point. If any-one else does attempt this then be warned that `Engine` and `Runner` are both defined in terms of each other (`Runner` uses `Engine` repeatedly and `Engine.run` is an alias of `Runner.run`). I pushed this up into `main.js` but I think it could be avoided by defining `Engine.run = function() { require('Runner').run() }`.

I've been trying to work out how react's (https://github.com/facebook/react) build works. I believe they move all their src files to a temporary lib directory before running browserify which means the requires become `require(Foo)` even if Foo is in a different folder (this seems preferable to the long requires in my fork). It also exposes the src files as `react/lib/*` when requiring as a third party (https://github.com/Izzimach/react-pixi/blob/master/src/ReactPIXI.js#L26-L35 is a good example). I'll continue to try and piece together their build to imitate this behaviour.

- [ ] remove unnecessary closures and re-indent (if we used js-beautify or an equivalent then this can be automated with minimal diff)

**Comment by Chrisui** [comment] 2015-05-01 18:54
Hey! Thought I'd drop a few thoughts in here.

1. Why not add a babel transpilation step in here so we can use es6 module syntax? This step would also allow us to take advantage of any other new spec features. Obviously you want to be careful of performance here but babel is super efficient and simple features such as default parameter values would help clean up the codebase in many places. Babel would also make the npm publishing super simple. In answer to "how to react do it" and how do many other libraries do it - it's basically just [this line](https://github.com/Chrisui/react-hotkeys/blob/master/scripts/build-npm#L4) - feel free to checkout the other scripts on that repo such as `release` which could help!
2. Use [eslint](http://eslint.org/) for linting. It's much more extensible and basically the new goto linter with as much 3rd party supper as jshint or any others.
3. I agree you should wait until a release candidate of matter v1.0 is ready and then do this nasty convert all the module syntax business for that.
4. No strong feelings towards jsbeautifier step - I think it should maybe just be ran one time when v1.0 is packaged up and then have an [.editorconfig](http://editorconfig.org/) which will basically remove any  other inconcistencies when people are contributing (doubt many people use an ide which doesn't support this now)
5. Use [webpack](http://webpack.github.io/) for packaging would be my recommendation over browserify - for the basic stuff I think there's no telling the difference between the two (they have very similar basic api's) but webpack (i've used both quite extensively) has reduced headache so much more.

**Comment by liabru** [comment] 2015-05-23 13:19
@hfaulds 

I've now merged my latest changes in to master, so I'm looking at implementing this soon.

I think it's best as you are suggesting: I can merge this in two stages, build file, require calls and exports (these are mostly just additions so they won't conflict).

Then following that I will do a cleanup commit to remove the closures and extra indentation. This way the changes will be separated to make things clear.

As for the circular dependencies caused by aliases, it makes sense just to move them to main since there shouldn't be many.

@Chrisui 

> Why not add a babel transpilation step in here so we can use es6 module syntax?

Yeah I've toyed with the idea of babel and es6 too. But I think this may possibly cause problems for some users who need support for IE < 10 if we start using certain features. It might also be quite tricky to debug at times even with source maps.

> Babel would also make the npm publishing super simple.

Hmm could you explain? Matter.js is already on npm, if we get browserify set up then it should work in node just fine?

>  In answer to "how to react do it" and how do many other libraries do it - it's basically just this line

Hmm so what's in the react build that we need here? I don't think I'm up to speed on this yet!

> Use eslint for linting

Sure I'll look into this.

> I agree you should wait until a release candidate of matter v1.0 is ready and then do this nasty convert all the module syntax business for that.

Actually I think I want to do this before then, since I'm considering splitting some of the functionality into plugins before 1.0 and proper dependencies are needed to do it. Going forward this way I can keep the core tight, but also build more extensions that people keep asking for without feeling so much feature creep guilt.

> No strong feelings towards jsbeautifier step

I may use it to help during the merge, but probably not as part of the build script. I find that beautifiers often mess up some intentional formatting styles that I like to use, even if I configure them.

> Use webpack for packaging would be my recommendation over browserify - for the basic stuff I think there's no telling the difference between the two (they have very similar basic api's) but webpack (i've used both quite extensively) has reduced headache so much more.

I need to look into webpack, but browserify's output looks just fine to me. Personally I just want as little overhead as possible and to maintain the exact same namespacing as before. 

What sort of headaches could we run into here? How does webpack solve them?

Thanks for the input guys.

**Comment by liabru** [comment] 2015-06-04 19:58
So far I've managed to implement browserify using @hfaulds fork!

It's not complete yet though, for some reason the Composite Manipulation fails because of a bad dependency `Body.translate is not a function` because `Body` is an empty object but other modules are using it just fine. So I'm not sure why this happens yet.

You can try this out in the [browserify branch](https://github.com/liabru/matter-js/tree/browserify).

**Comment by hfaulds** [comment] 2015-06-05 08:20
@liabru I ran into that when modules were loading in an infinite loop. If module A requires B requires A then you end up with undefined. Is it plausible something similar is happening here?

**Comment by liabru** [comment] 2015-06-05 15:16
Possibly, but my guess is if that were the reason then there'd be far more cases of this issue than just this one. Either way, I was expecting that browserify would easily be able to handle circular module references since this all happens at runtime...

**Comment by hfaulds** [comment] 2015-07-11 14:31
Just checked in on this branch, seems to be working fine now?

**Comment by liabru** [comment] 2015-07-11 15:03
Nope try all the demos, there should still be one that exhibits the issue. I've not had chance to revisit this yet but I'm expecting to merge this when its fixed.

**Comment by liabru** [comment] 2015-08-13 22:08
I've resolved the issue, I had to move all of the `require` statements to below the `module.exports`.

Before I merge, are there any objections to merging the [browserify](https://github.com/liabru/matter-js/tree/browserify) branch into master?

**Comment by liabru** [comment] 2015-08-17 22:56
The [browserify](https://github.com/liabru/matter-js/tree/browserify) branch has merged into master.

I'm also using the `standalone` build option which outputs a UMD module so it should work everywhere and I've updated the `main` field in `package.json` so that it points to the latest edge build. This means installing via `npm` should also work correctly now.

Thanks @hfaulds and @Chrisui for your help. 
Please update the thread if you run into any issues!

**Closed by liabru** 2015-08-17 22:56 UTC
