### ISSUE TITLE
Weird chain behavior on external monitors.

### ISSUE THREAD

**Issue by cgknutt** [liabru/matter-js#789] opened 2019-10-31 16:26 UTC
Has anyone experienced the following behavior of chains acting weird when viewed on external monitors?  Below is a video showing the behavior.

https://www.dropbox.com/s/bvsovw6w19o2zmy/IMG_3613.mp4?dl=0

About to pull my remaining hair out, fingers crossed!

**Comment by udisun** [comment] 2019-11-14 07:46
> Has anyone experienced the following behavior of chains acting weird when viewed on external monitors? Below is a video showing the behavior.
> 
> https://www.dropbox.com/s/bvsovw6w19o2zmy/IMG_3613.mp4?dl=0
> 
> About to pull my remaining hair out, fingers crossed!

"link not found" when using the link you've provided.
I have the same issue but with collisions.
I drop a ball through a series of objects and on one monitor the route it takes is constant through an infinite replay of releasing the ball. as soon as I drag the chrome tab to a another monitor without changing the browser size, the ball starts to change it route.
also pulling my hair out

**Comment by udisun** [comment] 2019-11-14 14:17
> Has anyone experienced the following behavior of chains acting weird when viewed on external monitors? Below is a video showing the behavior.
> 
> https://www.dropbox.com/s/bvsovw6w19o2zmy/IMG_3613.mp4?dl=0
> 
> About to pull my remaining hair out, fingers crossed!

Found the reason, hope this helps you too
https://stackoverflow.com/questions/58856537/matter-js-monitor-affects-the-engine-physics/58858869#58858869

**Comment by cgknutt** [comment] 2019-11-14 14:51
Thanks man, that’s perfect!

**Comment by liabru** [comment] 2020-03-06 12:37
The issue is that the built in runner is pretty simplistic and assumes a 60hz monitor, but now that monitors are coming with higher refresh rates this is becoming a problem. 

I've actually already been working on some improvements to the runner which will solve this. Thanks for reporting but closing this one as it's a known issue.

**Closed by liabru** 2020-03-06 12:37 UTC
Labels: bug, duplicate

**Comment by cgknutt** [comment] 2020-03-06 12:39
Thanks for replying man, that was it! Have a good one!
