### ISSUE TITLE
Depth / 'zIndex'

### ISSUE THREAD

**Issue by benorudolf** [liabru/matter-js#699] opened 2018-12-13 13:24 UTC
Hi, 

Tried searching for any solution to this but seem to hit a block. 
Is there a built in way to control the "depth hierarchy" of the objects in the world? 
Basically, like zIndex in CSS or the _bring-to-front, send-to-back_ functionality in some software.

If not built-in, what is the best way one could control it? I've found that most object are set based on the sequence you add them to the world i.e. last one is in front. 
This seems to work for rigid items. A composite soft body in my case is always in front, regardless of when it is added. 

Any help or guidance is greatly appreciated!

**Comment by liabru** [comment] 2019-01-13 00:40
Thanks for responding @Wesxdz, indeed there's a feature request for this in #243, which also includes an example implementation you can use in the meantime. It would be a nice feature for sure so I'll look into it when I get chance. 

@Wesxdz sounds cool, if you'd like to give it a go just check out the repo and use `gulp dev` to start the development environment, then submit a pull request (don't include any builds, just src changes).

I'm going to close this thread as a duplicate of #243, please feel free to discuss in that thread, thanks.

**Closed by liabru** 2019-01-13 00:40 UTC
