### ISSUE TITLE
Lags related to Grid.update

### ISSUE THREAD

**Issue by YChebotaev** [liabru/matter-js#141] opened 2015-08-23 02:54 UTC
Hello.

I have huge world and i experience strange behavior of engine. I need to to create many objects in scene (bullets) and also i have many objects (more than 600).

When i have many objects i experience lags when also add many objects to scene*. And when i have not so many objects (about 100), i experience lags when do not add another objects to a scene, and also when i do so, there is no more lags for some time.
I have very big `bucketWidth` and `bucketHeight` both equals 700. And also i have `positionIterations` 12 and `velocityIterations` 8 but this make no difference to described lags.

\* It's temporary objects (bullets as i said). After some time they removed from world. I experience lags in time that i continuously add new objects, and all ok when i stop do so.

I was do some research and was investigate that it's something related to `Grid.update` method and it's `forceUpdate` mode. First of all `Grid.update` are not optimized in google chrome due to large amount of opt/deopt cycles. I can solve this issue by this little snippet:

``` javascript
if (forceUpdate)
            return Grid.updateForce(grid, bodies, engine, forceUpdate)
```

At the top of `Grid.update` method. `Grid.updateForce` is a simple copy-paste code from `Grid.update`. Google chrome can optimize this, and i propose to replace all occurences of `Grid.update(grid, bodies, engine, true)` (all force updates of grid) with `Grid.updateForce`
But this is not solve the lags, just a little speed up.

I can suppose two improvements that can or cannot resolve this issue.
I think that using grid for broadphase structure is inefficient and it must be replaced to something as AABB tree.
And also i can propose to create somethings as `World.addFast` method that will add objects without forcing grid/tree rebuild.

Also when i turn on `showBroadphase`, i see that many grid regions are empty and because i see them in viewport, they exists in `grid.buckets` array. Maybe better remove empty buckets?

Can you comment something or explain the actual root of this issue?

**Comment by samredfern** [comment] 2016-01-21 15:32
It seems to be related to massive numbers of iterations over the region union, which seems to be in turn caused by a body which somehow has suddenly got an enormous bounds.

**Comment by liabru** [comment] 2016-06-26 20:19
The `forceUpdate` option is called when ever the world is modified (bodies added or removed) so if you're doing that very often (i.e. bullets) with a large amount of total bodies then you may get stuttering because it is quite expensive. 

The reason it is this way is because it was a tradeoff for keeping the overall design simple (it was one of the first modules I initially wrote). For it to be more efficient, the grid would need to know exactly what has been removed and then update buckets individually accordingly. This is possible but it would require additional modifications to `Matter.Composite` and `Matter.Engine` so it's not straightforward.

I'll label this one as an `improve` as I'd like to implement this eventually.

A temporary solution for for anyone with this problem:
I think there is a way you can batch this update, at least for body removals.

Rather than remove the bodies from the world do this instead:

1.  add the body to a `garbage` array
1.  set the body to sleep
1.  set the body collisionFilter so it is not colliding with anything
1.  stop rendering the body

Then when ever the `garbage` array gets to say `500` bodies, remove them all from the world in one step and clear the `garbage` array. This should mean the amount of times the grid is rebuilt is `1/500` times less.

**Comment by deniskrop** [comment] 2016-12-02 06:59
@liabru Are there any other methods to help with the stuttering issues now?

**Comment by Qriva** [comment] 2018-06-09 13:50
@liabru I wanted repeat the question. Can someone provide some good solution to fix it?
Do I break everything by adding `addFast` method without grid update?

For me personally problem exists becuase I am also adding bullets to the world but in my case it's single bullet but every 1 second. In result grid update eats a lot of computing power + later I get lags when GC tries to remove old grid buckets.
The worst thing is that I don't even remove these bodies yet so whole thing is only about adding bodies.

Any good solutions to that? _(except adding bodies before I use them but in my case it can be hard)_

**Comment by liabru** [comment] 2018-06-11 14:23
> Do I break everything by adding addFast method without grid update?

Most likely yes, there will be missed collisions on the new bodies in some cases, but maybe that's acceptable in your case?

> Any good solutions to that? (except adding bodies before I use them but in my case it can be hard)

Try being careful with collision filters, ensure that bullets can not collide with each other. I think that would help if you're not doing it already.

I realise the grid can be slow for adding bodies, this was a bit of a trade off to make the grid fast when running. It can certainly be improved though.

Also can you try using this fork, which has some improvements to grid that I hope to merge?
https://github.com/bchevalier/matter-js/tree/master/build

**Comment by Qriva** [comment] 2018-06-11 20:00
> Most likely yes, there will be missed collisions on the new bodies in some cases, but maybe that's acceptable in your case?

In general, what cases? When body is in other region of world than other objects?
I mean what kind of bug i can expect, no collision with old bodies or new bodies? I don't know how this part/module of matter works.

>Try being careful with collision filters, ensure that bullets can not collide with each other. I think that would help if you're not doing it already.

I didn't do it yet but how it helps, change how grid is updated? 
In my case, console said that:
![console](https://user-images.githubusercontent.com/29434176/41253535-f49f6782-6dc0-11e8-9231-9965e8f1ef04.jpg)

GC ate everything and I don't even remove bullets from the world yet, so just adding anything results in lags or low framerate. I could still change implementations of my objects to avoid adding new bodies but it would be way way better if I had workaround  - that's why I asked for something aka `fastAdd `too.

**Comment by fishmongr** [comment] 2021-12-08 22:59
It's 6 years later and it seems this major inefficiency is still the same? I ran into the same engine stuttering on removing bodies and traced it in the code to this Grid.update rebuilding from scratch on every body removal.  

> Also can you try using this fork, which has some improvements to grid that I hope to merge?
https://github.com/bchevalier/matter-js/tree/master/build

I want to test with this fork but it seems significantly behind master now. Any ETA on merging?

**Comment by liabru** [comment] 2021-12-20 10:48
As of the latest release [0.18.0](https://github.com/liabru/matter-js/pull/1069) the grid broadphase has been replaced, so I'll close this one as it should no longer be an issue. If anybody notices issues with the latest release like this then please do open a new issue, thanks.

**Closed by liabru** 2021-12-20 10:48 UTC
Labels: improve
