### ISSUE TITLE
Opposing constraints do not balance

### ISSUE THREAD

**Issue by rslack** [liabru/matter-js#93] opened 2015-05-14 17:55 UTC
[Opposing constraints do not balance, so the order in which constraints are added matters.](http://plnkr.co/edit/t709lZ9rTgfPE3OoyQiE)

I was not able to produce a working patch, but it seems like an issue in the way [difference is calculated](https://github.com/liabru/matter-js/blob/master/src/constraint/Constraint.js#L127) from a currentLength based on the body.position (postion after previuos constraints have been applied), rather then body.positionPrev (postion before any constraints have been applied).

Would it be better if stiffness was defined in terms of force per displacement (N/m), and forces only be applied in Constraint.postSolveAll? Or maybe even later, after collisions?

**Comment by liabru** [comment] 2015-05-14 18:50
Looks like the sample you linked is an incorrect link?

**Comment by SlackerCA** [comment] 2015-05-14 19:12
Fixed link above. I blame Pluker. http://plnkr.co/edit/t709lZ9rTgfPE3OoyQiE

**Comment by liabru** [comment] 2015-05-14 19:46
Great example! Looks like there's definitely something wrong here.
I think you're on the right track with the reason too. I'll see if I can get this sorted soon, thanks.

**Comment by SlackerCA** [comment] 2015-05-26 05:29
After much reading about physics engines and constraint resolution, I'm wondering if what we're seeing here is expected behavior, and the real issues here is expecting a *constraint* to behave like a *force*?

Changing the Constraint documentation would help, particularly by changing "The stiffness of constraints can be modified to create springs or elastic." since they don't work like springs (i.e. by applying forces).
> Constraints are used to decreases the degrees of freedom of upto two bodies. They are applied as a direct correction to the position/velocity of the bodies involved, and not as a force.
> The stiffness of constraints can be modified to create an effect similar to a spring or elastic, but without regard for mass or other forces.

And document the `stiffness` as 
>  A `Number` that specifies what fraction of the constraint violation which will be corrected each tick.
>  A value of `1` means the distance between the specified points will (if possible) be `constraint.length`.
>  A value of `0.2` means the distance between the specified points will (if possible) be adjusted only by 20% of the extra distance.

:green_heart: The code has been a real pleasure to read. :green_heart:

**Comment by sneakyfildy** [comment] 2016-05-27 21:56
Erm.  How are people supposed to create car suspension? What's with revolute joints?

**Comment by alelavoie** [comment] 2016-09-11 00:15
+1 to fix this issue.

**Comment by alelavoie** [comment] 2016-09-11 00:20
Can this be related to the fact that constraint chains start shaking like crazy when you pull them hard enough?

To reproduce, try pulling a chain in the chains demo :
http://brm.io/matter-js/demo/#chains

You need to pull hard enough so try pulling from the third link.

**Comment by liabru** [comment] 2016-09-11 08:53
@alelavoie I think so, there are a few problems with constraint stability that I need to look into. For now try increasing [engine.constraintIterations](http://brm.io/matter-js/docs/classes/Engine.html#property_constraintIterations).

**Comment by liabru** [comment] 2017-11-25 15:18
Closing this as it appears to have been solved by the constraint improvements made as of 0.13.0, thanks for providing the case.

**Closed by liabru** 2017-11-25 15:18 UTC
Labels: bug
