### ISSUE TITLE
Drag multiple items simultaneously?

### ISSUE THREAD

**Issue by mpirdis** [liabru/matter-js#290] opened 2016-09-20 09:17 UTC
Hello,

I am working on a project which is similar to to the beach balls example [http://brm.io/matter-js/demo/#beachBalls]. Because the project will run on touch screens i'd like the user to be able to drag multiple items at the same time. I tried to create a new MouseConstraint every time a touch is detected but with no luck. 
Is there a way to achieve this? I can't find any example with multiple drag

**Comment by liabru** [comment] 2016-09-20 10:55
There's nothing built in for this currently, the included `Matter.Mouse` only supports a single cursor. Multitouch would be a nice to have but it's not a priority for this project.

If you'd like to try it my suggestion is to take a look at the code for [Matter.Mouse](https://github.com/liabru/matter-js/blob/master/src/core/Mouse.js) and [Matter.MouseConstraint](https://github.com/liabru/matter-js/blob/master/src/constraint/MouseConstraint.js). If you manage to crack it, please send a pull request!

Could you +1 issue #159? Thanks.

**Comment by mpirdis** [comment] 2016-09-20 11:37
Thanks for the quick reply.
I'll try your suggestion and i'll let you know if i have any progress on it

**Comment by lilumat** [comment] 2016-11-18 14:29
Hello @mpirdis 
Have you work on PR for multitouch ?
I can make test if you want because it's a feature which I need in my project.
Best regards

**Comment by shaharhalutz** [comment] 2018-01-26 11:11
Hello @mpirdis and @lilumat
any progress on this issue ?
Best regards

**Comment by liabru** [comment] 2023-04-02 23:31
Closing as a duplicate of #159.

**Closed by liabru** 2023-04-02 23:31 UTC
Labels: duplicate, feature-request
