### ISSUE TITLE
Matter.Events on mousedown stopped working

### ISSUE THREAD

**Issue by holoverse** [liabru/matter-js#222] opened 2016-03-05 18:40 UTC
I was using 0.8.0 and I wanted to find the angle between the mouse and a selected object.  But before I even got to that point, I figured Id need to update to 0.9.1 so that I could use the Body.setAngle() method which didnt exist in 0.8.

But now after the update, the code below stopped working.  The mousemove event doesnt fire.
And common.random seems to output the same random numbers everytime?

var Events = Matter.Events;
var Common = Matter.Common;
Events.on(engine, "mousemove",  function(event) {
       var r =  Common.random(6,60); 
       console.log(r);
        console.log(event);
}

For now, I have just switched to using document event listeners for mouse events, no biggie.
Just wondering why this stopped working.

Also....Im just calculating the angle between the mouse and a rectangle body, and using Body.setAngle to set the angle.  However, visually, the rectangle spins wildly, and doesnt face the angle Im setting at all.

**Comment by liabru** [comment] 2016-03-06 23:56
If I remember correctly, those events got moved to `Matter.MouseConstraint` see [docs](http://brm.io/matter-js/docs/classes/MouseConstraint.html#events). So you'd need to catch the event on your mouse constraint rather than the engine.

As for `Common.random` it is seeded, so if you refresh the page the same sequence will appear (but the sequence should be pseudo random). This is intentional to make testing easier.

Regarding the body angle issue, I'm not sure, do you have a jsfiddle I can see?

**Comment by liabru** [comment] 2016-04-05 23:02
The angle issue might be caused by using degrees instead of radians? Closing now as assumed fixed.

**Closed by liabru** 2016-04-05 23:02 UTC
Labels: question
