### ISSUE TITLE
High-speed bodies lead to lags on grid broadphase

### ISSUE THREAD

**Issue by fominvic81** [liabru/matter-js#922] opened 2020-10-16 20:32 UTC
I find issue in broadphase, if velocity of body is very big then this code:
`var union = Grid._regionUnion(newRegion, body.region);`
Will return very big region, and it will lead to lags in this code:
`for (col = union.startCol; col <= union.endCol; col++) {`
`for (row = union.startRow; row <= union.endRow; row++) {`
`...`
`}`
`}`
Because count of rows and columns becomes large

**Comment by liabru** [comment] 2020-12-28 23:32
Interesting, do you know the cause of the high velocities?

Hopefully it's possible for you to avoid them in your project for now, but I've been thinking of implementing a velocity limiting feature which might help out here.

**Comment by liabru** [comment] 2021-12-20 10:41
As of the latest release [0.18.0](https://github.com/liabru/matter-js/pull/1069) the grid broadphase has been replaced, so I'll close this one as it should no longer be an issue.

**Closed by liabru** 2021-12-20 10:41 UTC
Labels: investigate, need-more-info
