### ISSUE TITLE
Resizing world makes bodies moving by themselves 

### ISSUE THREAD

**Issue by Danetag** [liabru/matter-js#50] opened 2014-12-03 15:01 UTC
Hi!

I don't know if I'm doing that right, but I would like to use the engine in fullscreen. So on window resize, I'm adjusting the world bounds:

engine.world.bounds.max.x = window.width;
engine.world.bounds.max.y = window.height;

When I'm doing that, all the none-static bodies are moving by themselves to the right, without any interaction :/

What's happening? Is there any method to resize the world?

Thanks!

**Comment by liabru** [comment] 2015-01-01 22:57
I can't reproduce your issue by changing the bounds max as you said in your first post.
Can you provide an example?

**Comment by liabru** [comment] 2015-05-24 13:50
I think this will no longer be an issue as of #67 so closing. Please update if this is still a problem.

**Closed by liabru** 2015-05-24 13:50 UTC

**Comment by vtheviking** [comment] 2015-07-20 19:01
Hey i noticed that im experiencing the same problem. Im trying to use
var h = window.height;
var w = window.width;
engine.world.bounds.max.x = w;
engine.world.bounds.max.y = h;
function resizeCanvas() {
 window.addEventListener('resize', resizeCanvas, false);
            canvas.width = window.innerWidth;
            canvas.height = window.innerHeight;

    resizeCanvas();
but it doesn't seem to be resizing my canvas element. Im trying to get the canvas to adjust its height and width according to the size of the viewport or window screen and change as the screen resizes, i looked at issue #67, and i made the post at #118. Im not seeing any results yet, and if you can point me in the right direction for objects sticking to the "ground" or set boundaries like at the website www.berberianmysterytheatre.com you could see the objects settling or sticking to a boundary after about 20seconds or so. 

Thanks again btw.

**Comment by liabru** [comment] 2015-07-20 19:37
Are you using the latest master build? If not then switching to it will resolve this.

**Comment by vtheviking** [comment] 2015-07-20 19:51
I don't think so, ill implement the new build and see how it turns out, and update the issue. 
thanks though!!

**Comment by jacobclarke92** [comment] 2020-02-06 06:35
I'm experienced this issue too but on phaser's (currently 3.22.0) implementation of MatterJS.
I worked out it was because I wasn't updating world bounds upon window resize, so at a certain point the right hand bound wall would pass over my character's hitbox and either force them to move left or right depending on which side of the wall they were closer to. 

Normally this might be fine / unnoticeable  but because I was repositioning the character to the centre of the screen each frame and moving everything else based on that difference from the center point, it meant that my whole world perpetually whizzed by at particular screen aspect ratios.

This might help someone so figured I'd post, no need to re-open.
