### ISSUE TITLE
Rethinking of Math.min/max functions (perfomance suggest)

### ISSUE THREAD

**Issue by TheLucifurry** [liabru/matter-js#1022] opened 2021-06-17 09:23 UTC
Hi)

[This benchmark](https://www.measurethat.net/Benchmarks/Show/13493/0/mathmaxmin-vs-function-ternary) shows, that native Math functions might be less perfomant than custom realisations on ternary operator

**I suggest to replace all the usings Math.min & Math.max functions to custom realisations**
I can do it itself, but i don't know, how you testing the pefomance of engine

**Are there any reasons why we shouldn't do this?**

**Comment by AurangAsif** [comment] 2021-06-17 15:35
I tried it out and the very first test showed all ternary variants to be fastest:
![image](https://user-images.githubusercontent.com/78823336/122428107-a27ee500-cf5f-11eb-8117-34be508d69eb.png)

However, on later runs Math variants catched up but were still behind. I assume this has to do with some sort of optimization from running the tests multiple times.

Anyways, my best guess to why Math is slow because you can pass more than 2 numbers to min/max and have the highest/lowest returned respectively. The implementation probably has extra overhead because of that.

Just giving my thoughts...

**Comment by Wexelus** [comment] 2021-06-18 01:38
Yes, most likely Math functions are slower due to the dynamic number of parameters
However, after examining the source code of Matter.js, I did not find cases of passing more than 2 parameters in Math functions

Also, I [updated the benchmark](https://www.measurethat.net/Benchmarks/Show/13493/1/mathmaxmin-vs-function-ternary-vs-inline-ternary) by adding "ternary inline" variants

**Comment by liabru** [comment] 2021-06-26 19:08
Thanks for reporting, I can confirm it helps as I've been working on a pure performance branch that includes this, plus a bunch of other things :) I'm working on wrapping it up, so will post back here when it's ready.

**Comment by liabru** [comment] 2023-03-16 00:05
Th performance branch changes were merged a while back as part of `0.18.0` after a lot of benchmarking. At the time, surprisingly `Math.min` appeared better in some very specific cases, so I think it will remain for now until revisited.

**Closed by liabru** 2023-03-16 00:05 UTC
