### ISSUE TITLE
Real circle implementation

### ISSUE THREAD

**Issue by reececomo** [liabru/matter-js#1191] opened 2023-01-16 03:12 UTC
/Just curious if there is an implementation of real circles available in another branch - it's been referenced a few times [#511](https://github.com/liabru/matter-js/issues/511#issuecomment-344117335) [#934](https://github.com/liabru/matter-js/issues/934) [#1190](https://github.com/liabru/matter-js/issues/1190#issuecomment-1383265156)

A plain ball bouncing on a flat surface is shooting off in all sorts of weird directions --> bouncing is wildly inconsistent, and no value of `maxSides`.

**Comment by liabru** [comment] 2023-04-02 23:39
Closing as a duplicate of #301.

I'll keep this in mind but please use that thread and see the suggestions there, thanks.

**Closed by liabru** 2023-04-02 23:39 UTC
Labels: duplicate, feature-request

**Comment by reececomo** [comment] 2023-04-03 00:46
Thanks for the response @liabru - we did see #301 at the time (and tried your suggestions, but with no luck).

**Comment by reececomo** [comment] 2023-04-03 00:59
For future readers - our game simulation leans heavily on ball physics, so we ended up using a different engine.

**Comment by KaliaJS** [comment] 2023-04-08 16:54
@reececomo What engine are you using instead?
