### ISSUE TITLE
How to prevent relative angle change between constrained bodies?

### ISSUE THREAD

**Issue by gamecubate** [liabru/matter-js#131] opened 2015-08-01 02:21 UTC
I have a constraint set on 2 bodies. As I apply a force to one of the bodies, the relative angle between it and the other body changes. I don't want that. Box2D supports joint limits allowing one to do just that. Is there any way to do this with matter-js?

**Comment by liabru** [comment] 2015-08-02 18:43
Duplicate of #71, please +1!

**Closed by liabru** 2015-08-02 18:43 UTC
