### ISSUE TITLE
IntelliSense (VSCode) isn't working with Matter.js

### ISSUE THREAD

**Issue by AgentCoulson612** [liabru/matter-js#996] opened 2021-04-12 11:09 UTC
I've been trying to get this to work for a while now, I've tried using the `import Matter from matter-js` (from the issue raised previously) after importing matter-js from npm, I even added the file directly into my project files, but nothing seems to work, here's my repo: [https://github.com/AgentCoulson612/Project-28](url)

**Comment by AgentCoulson612** [comment] 2021-04-12 11:10
![Uploading Screenshot 2021-04-12 at 4.40.23 PM.png…]()

**Comment by liabru** [comment] 2021-04-14 22:44
This is a duplicate of #961, so please use that thread to discuss this issue.

Looking at the project you linked, the matter.js version you are using is `matter-js 0.12.0` which is from 2017.

Try upgrade it first and respond in the other thread #961 if you have further issues, thanks.

(just to be sure I tested intellisense again using the latest release 0.17.0 through npm and it works fine for me)

**Closed by liabru** 2021-04-14 22:44 UTC
Labels: duplicate
